# 🎯 Notebook 04: Indexing and Selection

Time to slice and dice.

In this notebook, you'll:

- Use `.loc[]` for label-based selection
- Use `.iloc[]` for position-based selection
- Create boolean masks to filter rows
- Select specific columns and rows

This version uses a small built-in CSV created inside the notebook so it runs without needing `seaborn`.

In [1]:
import pandas as pd

# Create a small Titanic-like dataset for practice
csv_text = """name,age,sex,class,fare,survived,pclass,embarked
Allen,35,male,First,120.5,1,1,S
Beth,8,female,Second,25.0,1,2,C
Carlos,42,male,Third,7.9,0,3,S
Diana,29,female,First,80.0,1,1,Q
Ethan,4,male,Second,18.5,1,2,S
Fatima,55,female,First,150.0,1,1,C
George,13,male,Second,22.0,0,2,S
Hannah,38,female,Third,9.5,1,3,Q
Ian,,male,First,110.0,0,1,S
Julia,47,female,Second,30.0,1,2,C
Kevin,19,male,Third,8.1,0,3,S
Laura,62,female,First,200.0,1,1,C
Mason,2,male,Second,19.0,1,2,S
Nina,44,female,Second,28.0,1,2,Q
Omar,16,male,Third,7.5,0,3,S
Paula,,female,First,95.0,1,1,C
Quinn,51,male,Second,26.0,0,2,S
Rosa,11,female,Third,8.3,1,3,Q
Sam,33,male,First,130.0,1,1,S
Tina,41,female,Second,27.5,1,2,C
Uma,6,female,Second,21.0,1,2,S
Victor,70,male,First,160.0,0,1,C
Wendy,24,female,Third,9.0,1,3,Q
Xavier,14,male,Second,23.0,0,2,S
Yara,39,female,First,140.0,1,1,C
Zane,28,male,Third,8.7,0,3,S
"""

with open("mini_titanic.csv", "w") as f:
    f.write(csv_text)

df = pd.read_csv("mini_titanic.csv")
df.head(3)

     name   age     sex   class   fare  survived  pclass embarked
0   Allen  35.0    male   First  120.5         1       1        S
1    Beth   8.0  female  Second   25.0         1       2        C
2  Carlos  42.0    male   Third    7.9         0       3        S

## 🔎 Select rows by label with `.loc[]`

In [2]:
# .loc[row_label, column_label]
print(df.loc[0])

name        Allen
age          35.0
sex          male
class       First
fare        120.5
survived        1
pclass          1
embarked        S
Name: 0, dtype: object

In [3]:
# Row range (inclusive) with selected columns
df.loc[0:4, ["age", "fare", "sex"]]

    age   fare     sex
0  35.0  120.5    male
1   8.0   25.0  female
2  42.0    7.9    male
3  29.0   80.0  female
4   4.0   18.5    male

## 🔢 Select rows by position with `.iloc[]`

In [4]:
# iloc uses integer positions
df.iloc[0]

name        Allen
age          35.0
sex          male
class       First
fare        120.5
survived        1
pclass          1
embarked        S
Name: 0, dtype: object

In [5]:
# Row slice, column slice
df.iloc[1:4, 0:5]

     name   age     sex   class  fare
1    Beth   8.0  female  Second  25.0
2  Carlos  42.0    male   Third   7.9
3   Diana  29.0  female   First  80.0

## 🎯 Boolean Masking (Filtering)

In [6]:
# Filter passengers under age 10
kids = df[df["age"] < 10]
kids[["age", "sex", "class"]].head()

    age     sex   class
1   8.0  female  Second
4   4.0    male  Second
12  2.0    male  Second
20  6.0  female  Second

## 🧠 Compound Conditions

In [7]:
# Adults in First Class who paid over $100
rich_folks = df[(df["age"] > 18) & (df["class"] == "First") & (df["fare"] > 100)]
rich_folks[["age", "class", "fare"]].head()

     age  class   fare
0   35.0  First  120.5
5   55.0  First  150.0
11  62.0  First  200.0
18  33.0  First  130.0
21  70.0  First  160.0

## 🧹 Select Columns Only

In [8]:
df[["sex", "age", "embarked"]].head()

      sex   age embarked
0    male  35.0        S
1  female   8.0        C
2    male  42.0        S
3  female  29.0        Q
4    male   4.0        S

## 🎯 Your Turn

- Select the first row using `.iloc[]`, then again using `.loc[]`
- Slice the first 5 rows and select only `survived`, `sex`, and `age`
- Filter the dataset for female passengers over 40
- Create a DataFrame of passengers in 2nd class under age 15
- Use `.loc[]` to select the rows 10–20 and only the columns `fare`, `class`, and `age`

### 🎯 Bonus
Find passengers with missing age and print only their `name`, `age`, and `pclass`

In [9]:
# 1. First row using iloc and loc
print("First row with iloc:")
print(df.iloc[0])

print("\nFirst row with loc:")
print(df.loc[0])

# 2. First 5 rows with selected columns
print("\nFirst 5 rows with survived, sex, and age:")
print(df.loc[0:4, ["survived", "sex", "age"]])

# 3. Female passengers over 40
female_over_40 = df[(df["sex"] == "female") & (df["age"] > 40)]
print("\nFemale passengers over 40:")
print(female_over_40)

# 4. Passengers in 2nd class under age 15
second_class_kids = df[(df["class"] == "Second") & (df["age"] < 15)]
print("\n2nd class passengers under age 15:")
print(second_class_kids)

# 5. Rows 10–20 and only fare, class, and age
print("\nRows 10 to 20 with fare, class, and age:")
print(df.loc[10:20, ["fare", "class", "age"]])

# Bonus: missing age
missing_age = df[df["age"].isnull()][["name", "age", "pclass"]]
print("\nPassengers with missing age:")
print(missing_age)

First row with iloc:
name        Allen
age          35.0
sex          male
class       First
fare        120.5
survived        1
pclass          1
embarked        S
Name: 0, dtype: object

First row with loc:
name        Allen
age          35.0
sex          male
class       First
fare        120.5
survived        1
pclass          1
embarked        S
Name: 0, dtype: object

First 5 rows with survived, sex, and age:
   survived     sex   age
0         1    male  35.0
1         1  female   8.0
2         0    male  42.0
3         1  female  29.0
4         1    male   4.0

Female passengers over 40:
      name   age     sex   class   fare  survived  pclass embarked
5   Fatima  55.0  female   First  150.0         1       1        C
9    Julia  47.0  female  Second   30.0         1       2        C
11   Laura  62.0  female   First  200.0         1       1        C
13    Nina  44.0  female  Second   28.0         1       2        Q
19    Tina  41.0  female  Second   27.5         1       2        C

2nd class passengers under age 15:
      name   age     sex   class  fare  survived  pclass embarked
1     Beth   8.0  female  Second  25.0         1       2        C
4    Ethan   4.0    male  Second  18.5         1       2        S
6   George  13.0    male  Second  22.0         0       2        S
12   Mason   2.0    male  Second  19.0         1       2        S
20     Uma   6.0  female  Second  21.0         1       2        S
23  Xavier  14.0    male  Second  23.0         0       2        S

Rows 10 to 20 with fare, class, and age:
     fare   class   age
10    8.1   Third  19.0
11  200.0   First  62.0
12   19.0  Second   2.0
13   28.0  Second  44.0
14    7.5   Third  16.0
15   95.0   First   NaN
16   26.0  Second  51.0
17    8.3   Third  11.0
18  130.0   First  33.0
19   27.5  Second  41.0
20   21.0  Second   6.0

Passengers with missing age:
     name  age  pclass
8     Ian  NaN       1
15  Paula  NaN       1

## 🧼 Why This Matters

Being able to surgically select parts of your dataset is the core of real analysis.

Whether you're cleaning bad rows, exploring specific groups, or preparing data for a model, indexing and filtering give you control over the dataset.

Next: cleaning data with `.dropna()`, `.fillna()`, and other tools.