# 🧱 Column Operations: Creating, Renaming, and Dropping Columns

## Learning Goals

- Create new columns using calculations or functions
- Rename one or multiple columns
- Drop unwanted columns safely
- Apply functions across columns using `.apply()` and lambdas

## 🏗️ 1. Setup and Sample Data

In [1]:
import pandas as pd

data = {
    "first_name": ["Alice", "Bob", "Charlie", "David"],
    "last_name": ["Smith", "Jones", "Brown", "Wilson"],
    "math_score": [85, 90, 78, 92],
    "science_score": [88, 85, 82, 95]
}

df = pd.DataFrame(data)
df

  first_name last_name  math_score  science_score
0      Alice     Smith          85             88
1        Bob     Jones          90             85
2    Charlie     Brown          78             82
3      David    Wilson          92             95

## ➕ 2. Creating New Columns

In [2]:
# Simple column arithmetic
df["average_score"] = (df["math_score"] + df["science_score"]) / 2
df

  first_name last_name  math_score  science_score  average_score
0      Alice     Smith          85             88           86.5
1        Bob     Jones          90             85           87.5
2    Charlie     Brown          78             82           80.0
3      David    Wilson          92             95           93.5

In [3]:
# Create full name column
df["full_name"] = df["first_name"] + " " + df["last_name"]
df

,first_name,last_name,math_score,science_score,average_score,full_name
0,Alice,Smith,85,88,86.5,Alice Smith
1,Bob,Jones,90,85,87.5,Bob Jones
2,Charlie,Brown,78,82,80.0,Charlie Brown
3,David,Wilson,92,95,93.5,David Wilson

## ✍️ 3. Renaming Columns

In [4]:
# Rename selected columns
df = df.rename(columns={"math_score": "Math", "science_score": "Science"})
df

  first_name last_name  Math  Science  average_score      full_name
0      Alice     Smith    85       88           86.5    Alice Smith
1        Bob     Jones    90       85           87.5      Bob Jones
2    Charlie     Brown    78       82           80.0  Charlie Brown
3      David    Wilson    92       95           93.5   David Wilson

In [5]:
# Rename all columns to uppercase
df.columns = [col.upper() for col in df.columns]
df

  FIRST_NAME LAST_NAME  MATH  SCIENCE  AVERAGE_SCORE      FULL_NAME
0      Alice     Smith    85       88           86.5    Alice Smith
1        Bob     Jones    90       85           87.5      Bob Jones
2    Charlie     Brown    78       82           80.0  Charlie Brown
3      David    Wilson    92       95           93.5   David Wilson

## ❌ 4. Dropping Columns

In [6]:
# Drop by name
df = df.drop(columns=["FULL_NAME"])
df

  FIRST_NAME LAST_NAME  MATH  SCIENCE  AVERAGE_SCORE
0      Alice     Smith    85       88           86.5
1        Bob     Jones    90       85           87.5
2    Charlie     Brown    78       82           80.0
3      David    Wilson    92       95           93.5

## 🔁 5. Applying Functions Across Columns

In [7]:
# Categorize based on average score
def grade(score):
    if score >= 90:
        return "A"
    elif score >= 80:
        return "B"
    else:
        return "C"

df["GRADE"] = df["AVERAGE_SCORE"].apply(grade)
df

  FIRST_NAME LAST_NAME  MATH  SCIENCE  AVERAGE_SCORE GRADE
0      Alice     Smith    85       88           86.5     B
1        Bob     Jones    90       85           87.5     B
2    Charlie     Brown    78       82           80.0     B
3      David    Wilson    92       95           93.5     A

## 🧪 Try It Yourself

- Add a new column called `NAME_LENGTH` that contains the length of each `FIRST_NAME`
- Create a column `MATH_PLUS_5` which is the math score plus 5 bonus points

In [8]:
df["NAME_LENGTH"] = df["FIRST_NAME"].apply(len)
df["MATH_PLUS_5"] = df["MATH"] + 5
df

,FIRST_NAME,LAST_NAME,MATH,SCIENCE,AVERAGE_SCORE,GRADE,NAME_LENGTH,MATH_PLUS_5
0,Alice,Smith,85,88,86.5,B,5,90
1,Bob,Jones,90,85,87.5,B,3,95
2,Charlie,Brown,78,82,80.0,B,7,83
3,David,Wilson,92,95,93.5,A,5,97

## 🧠 Mini-Challenge

In [9]:
# Example workflow for data/students.csv
# Uncomment and adjust when your file exists.

# students = pd.read_csv("data/students.csv")
# students.head()

In [10]:
# Example solution pattern for the mini-challenge

# 1. Rename columns with spaces to underscores
# students.columns = [col.strip().replace(" ", "_") for col in students.columns]

# 2. Identify numeric test columns
# numeric_cols = students.select_dtypes(include="number").columns

# 3. Create total_score by summing numeric columns
# students["total_score"] = students[numeric_cols].sum(axis=1)

# 4. Drop columns that are all NaN
# students = students.dropna(axis=1, how="all")

# students.info()
# students.head()

## ✅ Worked Mini-Challenge Demo

This demo creates a small sample dataset so you can practice the exact steps even if `data/students.csv` is not available.

In [11]:
students = pd.DataFrame({
    "Student Name": ["Ana", "Luis", "Mia"],
    "Test 1": [85, 90, 88],
    "Test 2": [92, 84, 91],
    "Final Exam": [89, 87, 94],
    "Empty Column": [None, None, None]
})

students

  Student Name  Test 1  Test 2  Final Exam Empty Column
0          Ana      85      92          89         None
1         Luis      90      84          87         None
2          Mia      88      91          94         None

In [12]:
# Rename columns with spaces
students.columns = [col.strip().replace(" ", "_") for col in students.columns]

# Create total_score from numeric columns
numeric_cols = students.select_dtypes(include="number").columns
students["total_score"] = students[numeric_cols].sum(axis=1)

# Drop all-NaN columns
students = students.dropna(axis=1, how="all")

students

  Student_Name  Test_1  Test_2  Final_Exam  total_score
0          Ana      85      92          89          266
1         Luis      90      84          87          261
2          Mia      88      91          94          273

## 📝 Summary

| Action | Method |
|---|---|
| Create column | `df["new"] = ...` |
| Rename column(s) | `df.rename(columns={...})` |
| Rename all columns | `df.columns = [...]` |
| Drop column(s) | `df.drop(columns=[...])` |
| Apply function | `df["col"].apply(func)` |