# 🧮 Sorting & Filtering in Pandas

## Learning Goals

- Sort rows using `.sort_values()`
- Filter data using conditional logic
- Chain multiple filters together
- Use `.query()` for readable filtering

## 📥 1. Load the Dataset

In [1]:
import pandas as pd
from pathlib import Path

data_path = Path("../../data/students.csv")

if data_path.exists():
    df = pd.read_csv(data_path)
else:
    sample_data = {
        "first_name": ["Danielle", "Angel", "Joshua", "Jeffrey", "Jill", "Erica", "Bridget", "Craig"],
        "last_name": ["Wood", "Clark", "Adams", "Zuniga", "Wong", "Lynch", "Johnson", "Ferrell"],
        "math_score": [100, 67, 61, 77, 75, 74, 92, 94],
        "science_score": [95, 78, 100, 99, 83, 96, 100, 96]
    }
    df = pd.DataFrame(sample_data)

df.head()

  first_name last_name  math_score  science_score
0   Danielle      Wood         100             95
1      Angel     Clark          67             78
2     Joshua     Adams          61            100
3    Jeffrey    Zuniga          77             99
4       Jill      Wong          75             83

## 🔢 2. Sorting Data

In [2]:
# Sort by math_score
df.sort_values(by="math_score")

  first_name last_name  math_score  science_score
2     Joshua     Adams          61            100
1      Angel     Clark          67             78
5      Erica     Lynch          74             96
4       Jill      Wong          75             83
3    Jeffrey    Zuniga          77             99
6    Bridget   Johnson          92            100
7      Craig   Ferrell          94             96
0   Danielle      Wood         100             95

In [3]:
# Sort by science_score descending
df.sort_values(by="science_score", ascending=False)

  first_name last_name  math_score  science_score
2     Joshua     Adams          61            100
6    Bridget   Johnson          92            100
3    Jeffrey    Zuniga          77             99
5      Erica     Lynch          74             96
7      Craig   Ferrell          94             96
0   Danielle      Wood         100             95
4       Jill      Wong          75             83
1      Angel     Clark          67             78

In [4]:
# Sort by multiple columns
df.sort_values(by=["science_score", "math_score"], ascending=[False, True])

  first_name last_name  math_score  science_score
2     Joshua     Adams          61            100
6    Bridget   Johnson          92            100
3    Jeffrey    Zuniga          77             99
5      Erica     Lynch          74             96
7      Craig   Ferrell          94             96
0   Danielle      Wood         100             95
4       Jill      Wong          75             83
1      Angel     Clark          67             78

## 🧪 3. Filtering with Conditions

In [5]:
# Who scored at least 90 in math?
df[df["math_score"] >= 90]

  first_name last_name  math_score  science_score
0   Danielle      Wood         100             95
6    Bridget   Johnson          92            100
7      Craig   Ferrell          94             96

In [6]:
# Who scored less than 70 in either subject?
df[(df["math_score"] < 70) | (df["science_score"] < 70)]

  first_name last_name  math_score  science_score
1      Angel     Clark          67             78
2     Joshua     Adams          61            100

## 🔗 4. Combining Filters

In [7]:
# Students with B+ or higher in both
df[(df["math_score"] >= 87) & (df["science_score"] >= 87)]

  first_name last_name  math_score  science_score
0   Danielle      Wood         100             95
6    Bridget   Johnson          92            100
7      Craig   Ferrell          94             96

## 🧾 5. Using `.query()` for Readability

In [8]:
# Same query using .query()
df.query("math_score >= 87 and science_score >= 87")

  first_name last_name  math_score  science_score
0   Danielle      Wood         100             95
6    Bridget   Johnson          92            100
7      Craig   Ferrell          94             96

## 🧪 Try It Yourself

- Sort the dataset by first name alphabetically
- Find students with the same math and science score
- Use `.query()` to find students who scored over 95 in either subject

In [9]:
# Sort by first name alphabetically
df.sort_values(by="first_name")

  first_name last_name  math_score  science_score
1      Angel     Clark          67             78
6    Bridget   Johnson          92            100
7      Craig   Ferrell          94             96
0   Danielle      Wood         100             95
5      Erica     Lynch          74             96
3    Jeffrey    Zuniga          77             99
4       Jill      Wong          75             83
2     Joshua     Adams          61            100

In [10]:
# Students with the same math and science score
df[df["math_score"] == df["science_score"]]

Empty DataFrame
Columns: [first_name, last_name, math_score, science_score]
Index: []

In [11]:
# Students who scored over 95 in either subject
df.query("math_score > 95 or science_score > 95")

  first_name last_name  math_score  science_score
0   Danielle      Wood         100             95
2     Joshua     Adams          61            100
3    Jeffrey    Zuniga          77             99
5      Erica     Lynch          74             96
6    Bridget   Johnson          92            100
7      Craig   Ferrell          94             96

## 🧠 Mini-Challenge

In [12]:
# Load data/survey.csv when it exists in your project
# Uncomment and adjust as needed.

# survey = pd.read_csv("data/survey.csv")
# survey.head()

In [13]:
# Example mini-challenge workflow

# 1. Sort by the most recent signup date
# survey["signup_date"] = pd.to_datetime(survey["signup_date"], errors="coerce")
# survey = survey.sort_values(by="signup_date", ascending=False)

# 2. Filter out incomplete survey rows
# survey = survey.dropna(subset=["important_column"])
# survey = survey[survey["important_column"] != "N/A"]

# 3. Use query() for a custom condition
# survey.query("age >= 18 and score > 80")

## ✅ Demo Mini-Challenge

This small demo gives you something runnable even if `data/survey.csv` is not available.

In [14]:
survey = pd.DataFrame({
    "name": ["Ana", "Luis", "Mia", "Noah", "Sara"],
    "signup_date": ["2024-04-01", "2024-05-10", None, "2024-02-20", "N/A"],
    "completed": ["Yes", "No", "Yes", None, "Yes"],
    "score": [88, 72, 95, 60, 91]
})

survey["signup_date"] = pd.to_datetime(survey["signup_date"], errors="coerce")

# Sort by most recent signup date
survey_sorted = survey.sort_values(by="signup_date", ascending=False)
survey_sorted

   name signup_date completed  score
1  Luis  2024-05-10        No     72
0   Ana  2024-04-01       Yes     88
3  Noah  2024-02-20      None     60
2   Mia         NaT       Yes     95
4  Sara         NaT       Yes     91

In [15]:
# Filter out incomplete rows
survey_clean = survey_sorted.dropna(subset=["completed"])
survey_clean = survey_clean[survey_clean["completed"] != "N/A"]
survey_clean

   name signup_date completed  score
1  Luis  2024-05-10        No     72
0   Ana  2024-04-01       Yes     88
2   Mia         NaT       Yes     95
4  Sara         NaT       Yes     91

In [16]:
# Use query() with a chosen condition
survey_clean.query("score >= 90")

   name signup_date completed  score
2   Mia         NaT       Yes     95
4  Sara         NaT       Yes     91

## 📝 Summary

| Task | Code Example |
|---|---|
| Sort by column | `df.sort_values(by="col")` |
| Filter condition | `df[df["col"] > value]` |
| Combine filters | `df[(cond1) & (cond2)]` |
| Query method | `df.query("col > value and col2 < value")` |