# 🧪 Pandas Wrangle Lab: Clean & Explore a Real Dataset

## Learning Goals

- Practice loading, cleaning, and exploring real-world data
- Apply column creation, renaming, sorting, and filtering
- Use `.info()`, `.describe()`, and `.query()` fluently

## 📥 1. Load the Dataset

In [1]:
import pandas as pd
from pathlib import Path

data_path = Path("../../data/students.csv")

if data_path.exists():
    df = pd.read_csv(data_path)
else:
    # Fallback sample dataset so the notebook still runs
    df = pd.DataFrame({
        "first_name": ["Danielle", "Angel", "Joshua", "Jeffrey", "Jill", None, "Bridget", "Craig"],
        "last_name": ["Wood", "Clark", "Adams", "Zuniga", "Wong", "Lynch", "Johnson", None],
        "math_score": [100, 67, 61, 77, 75, 74, None, 94],
        "science_score": [95, 78, 100, None, 83, 96, 100, 96]
    })

df.head()

  first_name last_name  math_score  science_score
0   Danielle      Wood       100.0           95.0
1      Angel     Clark        67.0           78.0
2     Joshua     Adams        61.0          100.0
3    Jeffrey    Zuniga        77.0            NaN
4       Jill      Wong        75.0           83.0

## 🔎 2. Inspect and Audit the Data

In [2]:
# Basic overview
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   first_name     7 non-null      object
 1   last_name      7 non-null      object
 2   math_score     7 non-null      float64
 3   science_score  7 non-null      float64
dtypes: float64(2), object(2)
memory usage: 384.0+ bytes

In [3]:
# Summary stats
df.describe()

       math_score  science_score
count    7.000000       7.000000
mean    78.285714      92.571429
std     13.996598       8.599557
min     61.000000      78.000000
25%     70.500000      89.000000
50%     75.000000      96.000000
75%     85.500000      98.000000
max    100.000000     100.000000

## 🧼 3. Clean Missing or Invalid Data

In [4]:
# Check for missing values
df.isnull().sum()

first_name       1
last_name        1
math_score       1
science_score    1
dtype: int64

In [5]:
# Drop rows with missing names
df = df.dropna(subset=["first_name", "last_name"])

# Fill any missing scores with column average
df["math_score"] = df["math_score"].fillna(df["math_score"].mean())
df["science_score"] = df["science_score"].fillna(df["science_score"].mean())

df

  first_name last_name  math_score  science_score
0   Danielle      Wood       100.0           95.0
1      Angel     Clark        67.0           78.0
2     Joshua     Adams        61.0          100.0
3    Jeffrey    Zuniga        77.0           91.2
4       Jill      Wong        75.0           83.0
6    Bridget   Johnson        76.0          100.0

## 🧠 4. Feature Engineering (New Columns)

In [6]:
# Add average and grade
df["average_score"] = (df["math_score"] + df["science_score"]) / 2

def grade(score):
    if score >= 90:
        return "A"
    elif score >= 80:
        return "B"
    elif score >= 70:
        return "C"
    else:
        return "D"

df["grade"] = df["average_score"].apply(grade)
df.head()

  first_name last_name  math_score  science_score  average_score grade
0   Danielle      Wood       100.0           95.0           97.5     A
1      Angel     Clark        67.0           78.0           72.5     C
2     Joshua     Adams        61.0          100.0           80.5     B
3    Jeffrey    Zuniga        77.0           91.2           84.1     B
4       Jill      Wong        75.0           83.0           79.0     C

## 🔽 5. Sorting and Filtering

In [7]:
# Top performers
df[df["average_score"] > 90].sort_values(by="average_score", ascending=False).head()

  first_name last_name  math_score  science_score  average_score grade
0   Danielle      Wood       100.0           95.0           97.5     A

## 📊 6. Group and Describe by Grade

In [8]:
# How many of each grade?
df["grade"].value_counts()

grade
B    3
C    2
A    1
Name: count, dtype: int64

In [9]:
# Average scores per grade group
df.groupby("grade")[["math_score", "science_score", "average_score"]].mean()

       math_score  science_score  average_score
grade
A      100.000000      95.000000          97.50
B       71.333333      97.066667          84.20
C       71.000000      80.500000          75.75

## 💾 7. Save the Cleaned Dataset

In [10]:
df.to_csv("student_scores_cleaned.csv", index=False)

## 🧠 Challenge Task

In [11]:
# Filter out students who got a D, sort by last name, and export
d_students = df[df["grade"] == "D"][["first_name", "last_name", "grade"]].sort_values(by="last_name")
d_students.to_csv("d_students.csv", index=False)

d_students

Empty DataFrame
Columns: [first_name, last_name, grade]
Index: []

## 📝 Summary

This lab gives hands-on practice with:

- Cleaning nulls and missing values
- Creating new columns
- Filtering and sorting real data
- Grouping and summarizing by categorical features

Your data wrangling toolbox is getting solid.