# 🧼 Cleaning Dirty Data (Missing Values & Type Fixes)

## Learning Goals

- Detect and count missing values (`NaN`)
- Fill or drop missing data
- Convert column data types safely
- Understand the difference between `NaN`, `None`, `""`, and type mismatches

## 🧪 1. Load a Messy Dataset

In [1]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", None],
    "Age": ["25", "thirty", 35, np.nan, "40"],
    "Signup Date": ["2022-01-01", "not a date", "2022/03/01", None, "April 5, 2022"],
    "Score": [95.5, None, 88.0, 92.5, ""]
}

df = pd.DataFrame(data)
df

      Name     Age    Signup Date Score
0    Alice      25     2022-01-01  95.5
1      Bob  thirty     not a date  None
2  Charlie      35     2022/03/01  88.0
3    David     NaN           None  92.5
4     None      40  April 5, 2022

## 🧯 2. Detecting Missing or Broken Values

In [2]:
df.isnull()

    Name    Age  Signup Date  Score
0  False  False        False  False
1  False  False        False   True
2  False  False        False  False
3  False   True         True  False
4   True  False        False  False

In [3]:
df.isnull().sum()

Name           1
Age            1
Signup Date    1
Score          1
dtype: int64

In [4]:
df[df.isnull().any(axis=1)]

    Name     Age    Signup Date Score
1    Bob  thirty     not a date  None
3  David     NaN           None  92.5
4   None      40  April 5, 2022

Notice that an empty string `""` is not always counted as `NaN` automatically.  
That matters for columns like `Score`, where the blank value may still need cleaning.

## 🧹 3. Cleaning Strategy Options

In [5]:
df.fillna({
    "Name": "Unknown",
    "Age": -1,
    "Signup Date": "1970-01-01",
    "Score": 0.0
})

      Name     Age    Signup Date Score
0    Alice      25     2022-01-01  95.5
1      Bob  thirty     not a date   0.0
2  Charlie      35     2022/03/01  88.0
3    David      -1     1970-01-01  92.5
4  Unknown      40  April 5, 2022

In [6]:
df.dropna()

      Name Age Signup Date Score
0    Alice  25  2022-01-01  95.5
2  Charlie  35  2022/03/01  88.0

## 🧬 4. Data Type Fixes

In [7]:
df.dtypes

Name           object
Age            object
Signup Date    object
Score          object
dtype: object

In [8]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Score"] = pd.to_numeric(df["Score"], errors="coerce")
df["Signup Date"] = pd.to_datetime(df["Signup Date"], errors="coerce")
df.dtypes

Name                   object
Age                   float64
Signup Date    datetime64[ns]
Score                 float64
dtype: object

Using `errors="coerce"` turns bad values like `"thirty"` or `"not a date"` into `NaN`/`NaT`, which makes them easier to fix.

## 🩹 5. Impute (Fill In) Fixed Missing Values

In [9]:
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Score"] = df["Score"].fillna(df["Score"].mean())
df["Signup Date"] = df["Signup Date"].fillna(df["Signup Date"].min())
df["Name"] = df["Name"].fillna("Unknown")

df

      Name   Age Signup Date  Score
0    Alice  25.0  2022-01-01   95.5
1      Bob  35.0  2022-01-01   92.0
2  Charlie  35.0  2022-01-01   88.0
3    David  35.0  2022-01-01   92.5
4  Unknown  40.0  2022-01-01   92.0

## 🤓 6. Cleaned Data Review

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         5 non-null      object
 1   Age          5 non-null      float64
 2   Signup Date  5 non-null      datetime64[ns]
 3   Score        5 non-null      float64
dtypes: datetime64[ns](1), float64(2), object(1)
memory usage: 288.0+ bytes

In [11]:
df.describe(include="all")

         Name        Age          Signup Date     Score
count       5   5.000000                    5   5.00000
unique      5        NaN                  NaN       NaN
top     Alice        NaN                  NaN       NaN
freq        1        NaN                  NaN       NaN
mean      NaN  34.000000  2022-01-01 00:00:00  92.00000
min       NaN  25.000000  2022-01-01 00:00:00  88.00000
25%       NaN  35.000000  2022-01-01 00:00:00  92.00000
50%       NaN  35.000000  2022-01-01 00:00:00  92.00000
75%       NaN  35.000000  2022-01-01 00:00:00  92.50000
max       NaN  40.000000  2022-01-01 00:00:00  95.50000
std       NaN   5.477226                  NaN   2.66927

## 🧪 Try It Yourself

Modify the data dictionary at the top of this notebook. Add:

- A new column with some `None` and `""` values
- At least one row with all columns filled incorrectly

Then re-run the notebook and fix it step by step.

In [12]:
# Example practice version
practice_data = {
    "Name": ["Ana", "", None, "Leo", "??"],
    "Age": ["21", None, "old", "19", ""],
    "Signup Date": ["2023-01-01", "", "tomorrow", None, "2022-12-15"],
    "Score": [91, "", None, "88.5", "bad"],
    "City": ["Dallas", None, "", "Austin", "123"]
}

practice_df = pd.DataFrame(practice_data)
practice_df

   Name   Age Signup Date Score    City
0   Ana    21  2023-01-01    91  Dallas
1        None                      None
2  None   old    tomorrow  None
3   Leo    19        None  88.5  Austin
4    ??        2022-12-15   bad     123

In [13]:
# One possible cleaning pass for the practice data
practice_df = practice_df.replace("", np.nan)

practice_df["Age"] = pd.to_numeric(practice_df["Age"], errors="coerce")
practice_df["Score"] = pd.to_numeric(practice_df["Score"], errors="coerce")
practice_df["Signup Date"] = pd.to_datetime(practice_df["Signup Date"], errors="coerce")

practice_df["Name"] = practice_df["Name"].fillna("Unknown")
practice_df["City"] = practice_df["City"].fillna("Unknown")
practice_df["Age"] = practice_df["Age"].fillna(practice_df["Age"].median())
practice_df["Score"] = practice_df["Score"].fillna(practice_df["Score"].mean())
practice_df["Signup Date"] = practice_df["Signup Date"].fillna(practice_df["Signup Date"].min())

practice_df

      Name   Age Signup Date  Score     City
0      Ana  21.0  2023-01-01  91.00   Dallas
1  Unknown  20.0  2022-12-15  89.75  Unknown
2  Unknown  20.0  2022-12-15  89.75  Unknown
3      Leo  19.0  2022-12-15  88.50   Austin
4       ??  20.0  2022-12-15  89.75      123

## 🧠 Mini-Challenge

In [14]:
# Load "data/survey.csv" if you have it in your project.
# Uncomment and run the lines below when the file exists.

# survey = pd.read_csv("data/survey.csv")
# print(survey.isnull().sum())
# survey.info()
# survey.describe(include="all")

In [15]:
# Example cleaning pattern for survey.csv
# survey = survey.replace("", np.nan)
#
# for col in survey.columns:
#     print(col, survey[col].isnull().sum())
#
# Example conversions:
# survey["age"] = pd.to_numeric(survey["age"], errors="coerce")
# survey["signup_date"] = pd.to_datetime(survey["signup_date"], errors="coerce")
#
# Example fills:
# survey["age"] = survey["age"].fillna(survey["age"].median())
# survey = survey.dropna(subset=["important_column"])
#
# survey.info()
# survey.describe(include="all")

## 📝 Summary

| Concept | Tool/Function |
|---|---|
| Detect nulls | `df.isnull()`, `df.isnull().sum()` |
| Drop rows | `df.dropna()` |
| Fill values | `df.fillna()` |
| Convert types | `pd.to_numeric()`, `pd.to_datetime()` |
| Replace values | `df.replace()` |