# 04 - Data Input and Output

Most of data science is about loading data, exploring it, and saving results.

In this notebook you will learn:

- Reading CSV files with Pandas
- Inspecting DataFrames (`head`, `info`, `describe`)
- Writing data back to CSV
- Reading Excel files (if available)

## 1. Reading CSV Files

In [1]:
import pandas as pd

# Create a small CSV for demo
data = """Name,Age,Score
Alice,23,90
Bob,25,85
Charlie,22,95
"""

with open("students.csv", "w") as f:
    f.write(data)

# Read CSV into DataFrame
df = pd.read_csv("students.csv")
df

      Name  Age  Score
0    Alice   23     90
1      Bob   25     85
2  Charlie   22     95

### Your Turn

Create your own small CSV (3–5 rows) and read it into Pandas.

In [2]:
my_data_text = """Name,Age,Score
Alisson,21,88
Mia,20,92
Noah,22,79
Emma,19,95
"""

with open("my_students.csv", "w") as f:
    f.write(my_data_text)

my_df = pd.read_csv("my_students.csv")
my_df

      Name  Age  Score
0  Alisson   21     88
1      Mia   20     92
2     Noah   22     79
3     Emma   19     95

## 2. Exploring DataFrames

In [3]:
df.head()

      Name  Age  Score
0    Alice   23     90
1      Bob   25     85
2  Charlie   22     95

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Score   3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 200.0+ bytes

In [5]:
df.describe()

             Age  Score
count   3.000000    3.0
mean   23.333333   90.0
std     1.527525    5.0
min    22.000000   85.0
25%    22.500000   87.5
50%    23.000000   90.0
75%    24.000000   92.5
max    25.000000   95.0

### Your Turn

Use `.head()` to preview your dataset and `.describe()` to see basic statistics.

In [6]:
my_df.head()

      Name  Age  Score
0  Alisson   21     88
1      Mia   20     92
2     Noah   22     79
3     Emma   19     95

In [7]:
my_df.describe()

             Age      Score
count   4.000000   4.000000
mean   20.500000  88.500000
std     1.290994   6.952218
min    19.000000  79.000000
25%    19.750000  85.750000
50%    20.500000  90.000000
75%    21.250000  92.750000
max    22.000000  95.000000

## 3. Writing CSV Files

In [8]:
# Save the DataFrame to a new CSV
df.to_csv("students_copy.csv", index=False)
%ls *.csv

my_students.csv    students.csv       students_copy.csv

### Your Turn

Save your DataFrame to a CSV file called `my_data.csv`.

In [9]:
my_df.to_csv("my_data.csv", index=False)
%ls *.csv

my_data.csv        my_students.csv    students.csv       students_copy.csv

## 4. Reading Excel Files

In [11]:
%pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]1/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [12]:
# Optional: Requires 'openpyxl' installed
# Save to Excel
df.to_excel("students.xlsx", index=False)

# Read Excel file
pd.read_excel("students.xlsx")

      Name  Age  Score
0    Alice   23     90
1      Bob   25     85
2  Charlie   22     95

### Your Turn

Try saving your dataset to Excel and reading it back (if supported in your environment).

In [ ]:
my_df.to_excel("my_data.xlsx", index=False)
pd.read_excel("my_data.xlsx")

## Summary

- `pd.read_csv` loads data into a DataFrame.
- Use `.head()`, `.info()`, and `.describe()` to explore quickly.
- `df.to_csv` and `df.to_excel` save results.
- Pandas makes file I/O simple and reliable.